Concuerror v0.18-145-g3abcc5 started at 23 Mar 2018 15:20:45
 Options:
  [{after_timeout,infinity},
   {assertions_only,false},
   {assume_racing,false},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{observable_others,indep_obs,[]}},
   {exclude_module,[]},
   {files,["/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"]},
   {ignore_error,[deadlock]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,true},
   {non_racing_system,[]},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,5000},
   {treat_as_normal,[]},
   {use_receive_patterns,true}]
################################################################################
Interleaving #4
--------------------------------------------------------------------------------
Errors found:
* At step 17 process P exited abnormally
    Reason:
      {{badmatch,two},
       [{observable_others,indep_obs,0,
                           [{file,"/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"},
                            {line,192}]}]}
    Stacktrace:
      [{observable_others,indep_obs,0,
                          [{file,"/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"},
                           {line,192}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<observable_others.20.55111895>,[]])
    in erlang.erl line 2516
   2: P: P.2 = erlang:spawn(erlang, apply, [#Fun<observable_others.21.55111895>,[]])
    in erlang.erl line 2516
   3: P: P.3 = erlang:spawn(erlang, apply, [#Fun<observable_others.22.55111895>,[]])
    in erlang.erl line 2516
   4: P: P.4 = erlang:spawn(erlang, apply, [#Fun<observable_others.23.55111895>,[]])
    in erlang.erl line 2516
   5: P.2: {2,two} = P ! {2,two}
    in observable_others.erl line 163
   6: P.4: dependent = P ! dependent
    in observable_others.erl line 172
   7: P.3: independent = P ! independent
    in observable_others.erl line 168
   8: P.3: exits normally
   9: P.4: exits normally
  10: P: receives message (dependent)
    in observable_others.erl line 178
  11: P.2: {1,two} = P ! {1,two}
    in observable_others.erl line 164
  12: P.1: {1,one} = P ! {1,one}
    in observable_others.erl line 158
  13: P.1: {2,one} = P ! {2,one}
    in observable_others.erl line 159
  14: P.1: exits normally
  15: P.2: exits normally
  16: P: receives message ({1,two})
    in observable_others.erl line 191
  17: P: exits abnormally ({{badmatch,two},[{observable_others,indep_obs,0,[{file,[47,85,115,101,114,115,47,115,116|...]},{line,192}]}]})
################################################################################
Exploration completed!
################################################################################
Tips:
--------------------------------------------------------------------------------
* Increase '--print_depth' if output/graph contains "...".

################################################################################
Info:
--------------------------------------------------------------------------------
* Automatically instrumented module io_lib
* Instrumented & loaded module observable_others
* Automatically instrumented module erlang
* You can see pairs of racing instructions (in the report and '--graph') with '--show_races true'
* Continuing after error (-k)

################################################################################
Done at 23 Mar 2018 15:20:46 (Exit status: error)
  Summary: 1 errors, 4/4 interleavings explored
