Concuerror v0.18-145-g3abcc5 started at 23 Mar 2018 15:18:59
 Options:
  [{after_timeout,infinity},
   {assertions_only,false},
   {assume_racing,false},
   {depth_bound,500},
   {disable_sleep_sets,false},
   {dpor,optimal},
   {entry_point,{observable_others,indep_unobs,[]}},
   {exclude_module,[]},
   {files,["/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"]},
   {ignore_error,[deadlock]},
   {instant_delivery,true},
   {interleaving_bound,infinity},
   {keep_going,true},
   {non_racing_system,[]},
   {print_depth,20},
   {quiet,true},
   {scheduling,round_robin},
   {scheduling_bound_type,none},
   {show_races,false},
   {strict_scheduling,false},
   {symbolic_names,true},
   {timeout,5000},
   {treat_as_normal,[]},
   {use_receive_patterns,true}]
################################################################################
Interleaving #4
--------------------------------------------------------------------------------
Errors found:
* At step 13 process P.2 exited abnormally
    Reason:
      {{badmatch,[]},
       [{observable_others,'-indep_unobs/0-fun-1-',1,
                           [{file,"/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"},
                            {line,88}]}]}
    Stacktrace:
      [{observable_others,'-indep_unobs/0-fun-1-',1,
                          [{file,"/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"},
                           {line,88}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [named_table,public])
    in observable_others.erl line 78
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<observable_others.6.20844618>,[]])
    in erlang.erl line 2516
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<observable_others.7.20844618>,[]])
    in erlang.erl line 2516
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<observable_others.8.20844618>,[]])
    in erlang.erl line 2516
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<observable_others.9.20844618>,[]])
    in erlang.erl line 2516
   6: P.2: {2,two} = P ! {2,two}
    in observable_others.erl line 87
   7: P.4: dependent = P ! dependent
    in observable_others.erl line 96
   8: P.3: independent = P ! independent
    in observable_others.erl line 92
   9: P.3: exits normally
  10: P.4: exits normally
  11: P: receives message (dependent)
    in observable_others.erl line 102
  12: P.2: [] = ets:lookup(table, key)
    in observable_others.erl line 88
  13: P.2: exits abnormally ({{badmatch,[]},[{observable_others,'-indep_unobs/0-fun-1-',1,[{file,[47,85,115,101,114,115,47,115,116|...]},{line,88}]}]})
  14: P.1: true = ets:insert(table, {key,value})
    in observable_others.erl line 82
  15: P.1: {2,one} = P ! {2,one}
    in observable_others.erl line 83
  16: P.1: exits normally
################################################################################
Interleaving #5
--------------------------------------------------------------------------------
Errors found:
* At step 14 process P.2 exited abnormally
    Reason:
      {{badmatch,[]},
       [{observable_others,'-indep_unobs/0-fun-1-',1,
                           [{file,"/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"},
                            {line,88}]}]}
    Stacktrace:
      [{observable_others,'-indep_unobs/0-fun-1-',1,
                          [{file,"/Users/stavros.aronis/git/Concuerror/tests/suites/dpor_tests/src/observable_others.erl"},
                           {line,88}]}]
--------------------------------------------------------------------------------
Event trace:
   1: P: table = ets:new(table, [named_table,public])
    in observable_others.erl line 78
   2: P: P.1 = erlang:spawn(erlang, apply, [#Fun<observable_others.6.20844618>,[]])
    in erlang.erl line 2516
   3: P: P.2 = erlang:spawn(erlang, apply, [#Fun<observable_others.7.20844618>,[]])
    in erlang.erl line 2516
   4: P: P.3 = erlang:spawn(erlang, apply, [#Fun<observable_others.8.20844618>,[]])
    in erlang.erl line 2516
   5: P: P.4 = erlang:spawn(erlang, apply, [#Fun<observable_others.9.20844618>,[]])
    in erlang.erl line 2516
   6: P.2: {2,two} = P ! {2,two}
    in observable_others.erl line 87
   7: P.3: independent = P ! independent
    in observable_others.erl line 92
   8: P.3: exits normally
   9: P.4: dependent = P ! dependent
    in observable_others.erl line 96
  10: P.4: exits normally
  11: P: receives message (independent)
    in observable_others.erl line 102
  12: P: receives message ({2,two})
    in observable_others.erl line 104
  13: P.2: [] = ets:lookup(table, key)
    in observable_others.erl line 88
  14: P.2: exits abnormally ({{badmatch,[]},[{observable_others,'-indep_unobs/0-fun-1-',1,[{file,[47,85,115,101,114,115,47,115,116|...]},{line,88}]}]})
  15: P.1: true = ets:insert(table, {key,value})
    in observable_others.erl line 82
  16: P.1: {2,one} = P ! {2,one}
    in observable_others.erl line 83
  17: P.1: exits normally
################################################################################
Exploration completed!
################################################################################
Warnings:
--------------------------------------------------------------------------------
* Some errors were ignored ('--ignore_error').

################################################################################
Tips:
--------------------------------------------------------------------------------
* Increase '--print_depth' if output/graph contains "...".

################################################################################
Info:
--------------------------------------------------------------------------------
* Automatically instrumented module io_lib
* Instrumented & loaded module observable_others
* Automatically instrumented module erlang
* You can see pairs of racing instructions (in the report and '--graph') with '--show_races true'
* Continuing after error (-k)

################################################################################
Done at 23 Mar 2018 15:19:00 (Exit status: error)
  Summary: 2 errors, 5/5 interleavings explored
