################################################################################
Concuerror started with options:
  [{'after-timeout',infinite},
   {bound,-1},
   {distributed,true},
   {files,["/home/stavros/git/Concuerror/tests/suites/basic_tests/src/after_test_2.erl"]},
   {'light-dpor',false},
   {symbolic,true},
   {target,{after_test_2,after_test_2,[]}},
   {verbose,0},
   {wait,5000}]
################################################################################
Erroneous interleaving 1:
* Blocked at a 'receive' (when all other processes have exited):
    P in after_test_2.erl line 21
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<after_test_2.0.109760583>,[]])
    in erlang.erl line 2188
   2: P: receive timeout expired after 0 ms
    in after_test_2.erl line 11
   3: P: receive timeout expired after 0 ms
    in after_test_2.erl line 16
   4: P.1: one = P ! one
    in after_test_2.erl line 10
   5: Message (one) from P.1 reaches P
   6: P.1: exits normally
################################################################################
Erroneous interleaving 2:
* Blocked at a 'receive' (when all other processes have exited):
    P in after_test_2.erl line 21
--------------------------------------------------------------------------------
Interleaving info:
   1: P: P.1 = erlang:spawn(erlang, apply, [#Fun<after_test_2.0.109760583>,[]])
    in erlang.erl line 2188
   2: P: receive timeout expired after 0 ms
    in after_test_2.erl line 11
   3: P.1: one = P ! one
    in after_test_2.erl line 10
   4: P.1: exits normally
   5: Message (one) from P.1 reaches P
   6: P: receives message (one)
    in after_test_2.erl line 16
################################################################################
Done! (Exit status: completed)
  Summary: 2 errors, 2/2 interleavings explored
